imports:
    - { resource: tables.yml }

services:
    cabot.footericons.listener:
        class: cabot\footericons\event\listener
        arguments:
            - '@cache.driver'
            - '@config'
            - '@dbal.conn'
            - '@ext.manager'
            - '@path_helper'
            - '@template'
            - '%cabot.footericons.table%'
        tags:
            - { name: event.listener }

    cabot.footericons.acp_controller:
        class: cabot\footericons\controller\acp_controller
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@ext.manager'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'
            - '@cache.driver'
            - '@cabot.footericons.service'
            - '%cabot.footericons.table%'

    cabot.footericons.service:
        class: cabot\footericons\services\footericons_service
        arguments:
            - '@dbal.conn'
            - '%cabot.footericons.table%'
